name = "preview"
main = "src/worker.js"
compatibility_date = "2026-08-19"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[durable_objects]
bindings = [
  { name = "GAME_ROOMS", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[[d1_databases]]
binding = "DB"
database_name = "preview-history"
database_id = "8bff07c3-bffd-433a-adc9-1ea0a2b7c350"
migrations_dir = "migrations"
